### ISSUE TITLE
Div. Problemmeldungen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-link-checker#1]
Siehe hier:
https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/159

**Comment by mduven** [comment]
Hallo zusammen, ich wollte einmal nachfragen, ob bzgl. des "Ignorieren"-Buttons, der in obigem Link bereits angesprochen wurde, weitere Schritte geplant sind? Habe einige Links, die nicht fehlerhaft sind aber z.B. mit "Operation timedout" in der Liste auftauchen. Ebenso tauchen immer mal wieder veraltete Links aus alten Beiträgen auf. Viele Grüße! :)

**Comment by rvdforst** [comment]
Ignorieren-Button, Filter und Views hinzugefügt. Der Fehler bei der veralteten Links wurde behoben.
