### ISSUE TITLE
Function crate_function() is deprecated

### ISSUE THREAD

**Issue by mariohamann** [RRZE-Webteam/rrze-link-checker#5]
Hallo RRZE-Webteam!
Wir testen gerade euer Plugin und haben festgestellt, dass unser Log ziemlich zugeballert wird. `create_function()` wird wohl seit PHP 7.2 nicht mehr unterstützt, wird aber in [Worker.php (Zeile 32 + 38)](https://github.com/RRZE-Webteam/rrze-link-checker/blob/93ca738187487ec19e26b5e4c3f31fc6531c85ff/includes/Worker.php#L31) sowie [Dashboard.php (47 + 56)](https://github.com/RRZE-Webteam/rrze-link-checker/blob/93ca738187487ec19e26b5e4c3f31fc6531c85ff/includes/Dashboard.php#L47) verwendet. Es wird auch aus Sicherheits- und Performance-Gründen empfohlen, anonyme Funktionen nativ einzubinden: https://www.php.net/manual/de/function.create-function.php
Habt ihr vor, euch der Sache anzunehmen?
Grüße aus Freiburg!

**Comment by xwolfde** [comment]
@rvdforst schaust du mal? Lohnt sich das noch zu beheben? Eigentlich haben wir ja das Plugin vor einiger Zeit aus dem Portfolio entfernt. Wenn wir nicht weiter entwickeln, sollten wir das Repo als Archiv deklarieren.

**Comment by rvdforst** [comment]
Das ist richtig, dieses Repo wird weder weiterentwickelt noch werden die aktuellen Fehler behoben. Daher wird es archiviert.
Hintergrund: In einer Multisite-Installation ist das Überprüfen aller Links über dieses Plugin nicht effizient und erfordert zu viele Serverressourcen. Aus diesem Grund wird diese Aufgabe einem externen Dienst empfohlen.
